/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WardRouteImport } from './routes/ward'
import { Route as VoteRouteImport } from './routes/vote'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrioritiesRouteImport } from './routes/priorities'
import { Route as MeetTheCandidateRouteImport } from './routes/meet-the-candidate'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as IndexRouteImport } from './routes/index'

const WardRoute = WardRouteImport.update({
  id: '/ward',
  path: '/ward',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrioritiesRoute = PrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetTheCandidateRoute = MeetTheCandidateRouteImport.update({
  id: '/meet-the-candidate',
  path: '/meet-the-candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/get-involved': typeof GetInvolvedRoute
  '/meet-the-candidate': typeof MeetTheCandidateRoute
  '/priorities': typeof PrioritiesRoute
  '/privacy': typeof PrivacyRoute
  '/vote': typeof VoteRoute
  '/ward': typeof WardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/get-involved': typeof GetInvolvedRoute
  '/meet-the-candidate': typeof MeetTheCandidateRoute
  '/priorities': typeof PrioritiesRoute
  '/privacy': typeof PrivacyRoute
  '/vote': typeof VoteRoute
  '/ward': typeof WardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/get-involved': typeof GetInvolvedRoute
  '/meet-the-candidate': typeof MeetTheCandidateRoute
  '/priorities': typeof PrioritiesRoute
  '/privacy': typeof PrivacyRoute
  '/vote': typeof VoteRoute
  '/ward': typeof WardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/contact'
    | '/get-involved'
    | '/meet-the-candidate'
    | '/priorities'
    | '/privacy'
    | '/vote'
    | '/ward'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/contact'
    | '/get-involved'
    | '/meet-the-candidate'
    | '/priorities'
    | '/privacy'
    | '/vote'
    | '/ward'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/contact'
    | '/get-involved'
    | '/meet-the-candidate'
    | '/priorities'
    | '/privacy'
    | '/vote'
    | '/ward'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  MeetTheCandidateRoute: typeof MeetTheCandidateRoute
  PrioritiesRoute: typeof PrioritiesRoute
  PrivacyRoute: typeof PrivacyRoute
  VoteRoute: typeof VoteRoute
  WardRoute: typeof WardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ward': {
      id: '/ward'
      path: '/ward'
      fullPath: '/ward'
      preLoaderRoute: typeof WardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priorities': {
      id: '/priorities'
      path: '/priorities'
      fullPath: '/priorities'
      preLoaderRoute: typeof PrioritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-the-candidate': {
      id: '/meet-the-candidate'
      path: '/meet-the-candidate'
      fullPath: '/meet-the-candidate'
      preLoaderRoute: typeof MeetTheCandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  MeetTheCandidateRoute: MeetTheCandidateRoute,
  PrioritiesRoute: PrioritiesRoute,
  PrivacyRoute: PrivacyRoute,
  VoteRoute: VoteRoute,
  WardRoute: WardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
